server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/project-db
    username: root
    password: root123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework: DEBUG
